version: '3.8'

services:
 notes:
  build: .
  container_name: notes
  ports:
   - 3000:3000
  environment:
   - SERVER_PORT=3000
   - CONNECTIONSTRING=mongodb://mongo:27017/notes
  volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
  command: sh -c "yarn install&&yarn start"

 mongo:
  image: mongo:5.0
  container_name: mongo
  command: --replSet rs0
  volumes:
    - mongodb:/data/db
    - mongodb_config:/etc/mongod.conf
  expose:
    - 27017
  ports:
     - 27011:27017
  restart: always

 secondary:
  image: mongo:5.0
  container_name: secondary
  command: --replSet rs0
  volumes:
   - mongodbSecond:/data/db
  expose:
   - 27017
  ports:
     - 27012:27017
  restart: always

 mongodb-arbiter:
  image: mongo:5.0
  container_name: mongodb-arbiter
  command: --replSet rs0
  expose:
    - 27017
  ports:
    - 27013:27017
  restart: always
volumes:
  mongodb:
  mongodbSecond:
  mongodb_config:
  
