version: '3.8'

services:
 app:
  build: .
  container_name: app
  ports:
   - 3000:3000
  environment:
   - SERVER_PORT=3000
   - CONNECTIONSTRING=mongodb://mongo1:27017/app
  volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
  command: sh -c "yarn install && yarn run dev"

 mongo1:
  image: mongo:5.0
  container_name: mongo1
  volumes:
    - mongodb1:/data/db
    - mongodb1_config:/etc/mongod.conf
  expose:
    - 27017
  ports:
     - 27011:27017
  restart: always
volumes:
  mongodb1:
  mongodb1_config:
  