version: '3.8'

services:
 react-app:
  build:
   context: .
  ports:
   - 8000:8000
  environment:
   - PORT=8000
  volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
  command: sh -c "yarn install&&yarn start"